### ISSUE TITLE
[Code review: Contract Bugs]: Different storage structures used by proxy and logic (L1WrappedStakedTON)

### ISSUE THREAD

**Issue by Zena-park** [tokamak-network/gem-nft-contract#79]
### Describe the bug

The storage structure used by proxy and logic is different.

 https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/src/L1/L1WrappedStakedTONProxy.sol#L11
 
 https://github.com/tokamak-network/gem-nft-contract/blob/af6ef0f9bfd110c8ebec9c5fa83078e56f755c0c/src/L1/L1WrappedStakedTON.sol#L32-L37
 
** TreasuryProxy and Treasury also have the same error.
** RandomPackProxy and RandomPack also have the same error. 

### Impact

I don't know if it was intentional to set all storage visibility to internal, but if you set it to public and check the storage value in the proxy, you can see that they have different memory.

### Recommendation

To avoid confusion, remove the L1WrappedStakedTONStorage inheritance from L1WrappedStakedTONProxy. Or, make the memory configuration the same. (The logic has a different memory configuration due to ReentrancyGuard in the middle.)

**Comment by mehdi-defiesta** [comment]
@Zena-park Indeed, If I have set each variable as internal is because I was not getting the appropriate value when using storage getters generated by solidity on public variables. I deleted the storage inheritance from proxy contract. Here is the [commit](totalClaimableAmount user1:  100786802775075961596194660250) . All tests passed so I assume there is no storage issue anymore. Let me know if you want me to make further testing
